logLevel = "debug" # "debug" | "warn" | "error"
telemetry = false

[test]
root = "./tests"
coverage = true
coverageThreshold = { line = 0.7, function = 0.8, statement = 0.9 }
coverageSkipTestFiles = true